org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
kotlin.code.style=official

systemProp.http.proxyHost=<本机地址>
systemProp.http.proxyPort=<端口>
systemProp.https.proxyHost=<本机地址>
systemProp.https.proxyPort=<端口>

org.gradle.java.home=<本机 JDK 路径>
